allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

def buildDir = "${rootProject.projectDir}/../build"
rootProject.buildDir = "${buildDir}"
subprojects {
    project.buildDir = "${buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
